export const CHECKLIST_TEMPLATE = [
  // GENERAL - Contract & project start
  { item_id: "gen-proposal", category: "general", sub_section: "Contract & project start", phase: "SD", text: "Signed proposal / fee authorization on file for the project?" },
  { item_id: "gen-expansion", category: "general", sub_section: "Contract & project start", phase: "SD", text: "Need for future-expansion provisions verified and addressed?" },
  { item_id: "gen-kickoff", category: "general", sub_section: "Contract & project start", phase: "SD", text: "Project kickoff meeting held?" },
  { item_id: "gen-template", category: "general", sub_section: "Contract & project start", phase: "DD", text: "Typical sheets started from the AG&E SE standard templates (not another project)?" },
  { item_id: "gen-principal-loads", category: "general", sub_section: "Contract & project start", phase: "DD", text: "Design loads reviewed with a Principal?" },
  // GENERAL - Code & loads
  { item_id: "gen-loc", category: "general", sub_section: "Code & loads", phase: "SD", text: "Is the building location defined?" },
  { item_id: "gen-codeineffect", category: "general", sub_section: "Code & loads", phase: "SD", text: "Building code in effect verified?" },
  { item_id: "gen-asce", category: "general", sub_section: "Code & loads", phase: "SD", text: "Have ASCE 7 Hazards (wind / seismic / snow / ice) been obtained for the site?" },
  { item_id: "gen-code", category: "general", sub_section: "Code & loads", phase: "SD", text: "Has the code search been created and checked?" },
  { item_id: "gen-rc", category: "general", sub_section: "Code & loads", phase: "SD", text: "Risk Category & importance factors confirmed?" },
  { item_id: "gen-official", category: "general", sub_section: "Code & loads", phase: "SD", text: "All loadings verified with the Building Official (Contact Sheet completed)?" },
  { item_id: "gen-owner", category: "general", sub_section: "Code & loads", phase: "SD", text: "Owner's special structural loading requirements confirmed?" },
  { item_id: "gen-combos", category: "general", sub_section: "Code & loads", phase: "DD", text: "Governing load combinations (ASCE 7) established for the project?" },
  { item_id: "gen-crit", category: "general", sub_section: "Code & loads", phase: "DD", text: "Design criteria narrative drafted and shown on drawings?" },
  { item_id: "gen-wsasd", category: "general", sub_section: "Code & loads", phase: "DD", text: "Wind / seismic loads on drawings clearly noted as ASD or LRFD?" },
  { item_id: "gen-gravasd", category: "general", sub_section: "Code & loads", phase: "DD", text: "Gravity loads and reactions on drawings clearly noted as ASD or LRFD?" },
  { item_id: "gen-mep", category: "general", sub_section: "Code & loads", phase: "DD", text: "MEP equipment weights list completed from cut sheets, with weights increased by 10%?" },
  { item_id: "gen-units", category: "general", sub_section: "Code & loads", phase: "DD", text: "Consistent units & sign conventions across all software?" },
  // GENERAL - Vibration
  { item_id: "gen-vib", category: "general", sub_section: "Vibration", phase: "DD", text: "Floor and frame vibrations addressed?" },
  { item_id: "gen-vib-issue", category: "general", sub_section: "Vibration", phase: "DD", text: "Were any vibration issues identified during design?" },
  { item_id: "gen-vib-team", category: "general", sub_section: "Vibration", phase: "DD", text: "Vibration issues cleared with the Vibration Analysis team?" },
  // GENERAL - Rooftop screen walls
  { item_id: "gen-screen", category: "general", sub_section: "Rooftop screen walls", phase: "DD", text: "Does the project have rooftop screen walls?" },
  { item_id: "gen-screen-wind", category: "general", sub_section: "Rooftop screen walls", phase: "DD", text: "Additional wind loads from the screen walls included in the analysis?" },
  { item_id: "gen-screen-mass", category: "general", sub_section: "Rooftop screen walls", phase: "DD", text: "Mechanical loads behind the screen wall included in the roof mass for seismic?" },
  // GENERAL - Fire & life safety
  { item_id: "gen-fm-ask", category: "general", sub_section: "Fire & life safety", phase: "SD", text: "Architect confirmed whether the project must follow Factory Mutual (FM)?" },
  { item_id: "gen-fm-checklist", category: "general", sub_section: "Fire & life safety", phase: "DD", text: "FM checklist completed?" },
  { item_id: "gen-fire", category: "general", sub_section: "Fire & life safety", phase: "DD", text: "Do the floors and roof require a fire rating?" },
  { item_id: "gen-fire-slab", category: "general", sub_section: "Fire & life safety", phase: "DD", text: "Does the floor slab thickness satisfy the fire-rating requirement?" },
  { item_id: "gen-firesep", category: "general", sub_section: "Fire & life safety", phase: "DD", text: "Does the building require fire separations?" },
  { item_id: "gen-firesep-cols", category: "general", sub_section: "Fire & life safety", phase: "DD", text: "Double columns provided at the fire separations?" },
  // GENERAL - Sustainability
  { item_id: "gen-leed", category: "general", sub_section: "Sustainability", phase: "SD", text: "Is the building pursuing LEED (or a similar program)?" },
  { item_id: "gen-leed-spec", category: "general", sub_section: "Sustainability", phase: "DD", text: "Do the Submittals Table and Specifications reflect the LEED requirements?" },
  // GENERAL - Model coordination
  { item_id: "gen-slabedge", category: "general", sub_section: "Model coordination", phase: "DD", text: "Slab edge file approved by the Architect?" },
  { item_id: "gen-openings", category: "general", sub_section: "Model coordination", phase: "DD", text: "Confirmation email received from Architect and MEP that all openings are in the model?" },

  // METAL DECK
  { item_id: "md-grav", category: "metaldeck", phase: "DD", text: "Is gravity design complete for the deck (load tables vs. span / loading)?" },
  { item_id: "md-snow", category: "metaldeck", phase: "DD", text: "Was snow drift accounted for in the deck design?" },
  { item_id: "md-stiff", category: "metaldeck", phase: "DD", text: "Was stiffness checked for each deck region considering the actual attachment pattern?" },
  { item_id: "md-teq", category: "metaldeck", phase: "DD", text: "Is deck thickness correctly entered in TSD using the equivalent thickness?" },
  { item_id: "md-shear", category: "metaldeck", phase: "DD", text: "Diaphragm shear demand ≤ allowable for the chosen profile / fastening?" },
  { item_id: "md-collect", category: "metaldeck", phase: "DD", text: "Collector / drag forces and chord forces resolved and detailed?" },
  { item_id: "md-uplift", category: "metaldeck", phase: "DD", text: "Net wind uplift checked against deck attachment capacity?" },
  { item_id: "md-fmuplift", category: "metaldeck", phase: "DD", text: "FM Global uplift rating (e.g. 1-90) confirmed for the roof assembly?" },
  { item_id: "md-drift", category: "metaldeck", phase: "CD", text: "Is diaphragm drift below the established limit?" },
  { item_id: "md-gauge", category: "metaldeck", phase: "CD", text: "Deck type, gauge, finish & fastener / sidelap pattern specified on drawings?" },
  { item_id: "md-constr", category: "metaldeck", phase: "DD", text: "Bare-deck construction-stage load checked?" },

  // COMPOSITE DECK
  { item_id: "cmp-action", category: "compositedeck", phase: "DD", text: "Composite action parameters (stud qty / spacing) consistent with the model?" },
  { item_id: "cmp-studs", category: "compositedeck", phase: "DD", text: "Shear stud design (count, capacity, spacing limits) complete?" },
  { item_id: "cmp-wet", category: "compositedeck", phase: "DD", text: "Wet-concrete / construction (unshored) load checked?" },
  { item_id: "cmp-defl", category: "compositedeck", phase: "DD", text: "Pre-composite & composite deflection (and ponding) checked?" },
  { item_id: "cmp-fire", category: "compositedeck", phase: "DD", text: "Required fire rating / assembly thickness coordinated?" },
  { item_id: "cmp-diaph", category: "compositedeck", phase: "DD", text: "Composite floor diaphragm shear / stiffness checked?" },
  { item_id: "cmp-gauge", category: "compositedeck", phase: "CD", text: "Composite deck type, gauge & topping thickness specified on drawings?" },

  // STEEL - Framing & layout
  { item_id: "stl-template", category: "steel", sub_section: "Framing & layout", phase: "DD", text: "Steel framing started from the AG&E SE template?" },
  { item_id: "stl-girder-flange", category: "steel", sub_section: "Framing & layout", phase: "DD", text: "Big girders framed into the flanges of columns?" },
  { item_id: "stl-tw-girder", category: "steel", sub_section: "Framing & layout", phase: "DD", text: "Tilt-wall: do big girders frame into the edges of panels?" },
  { item_id: "stl-tw-girder-col", category: "steel", sub_section: "Framing & layout", phase: "DD", text: "Adding columns at those locations discussed with the Architect?" },
  { item_id: "stl-hoist", category: "steel", sub_section: "Framing & layout", phase: "DD", text: "Hoist beams provided where required in floor and roof framing?" },
  // STEEL - Design & analysis
  { item_id: "stl-grades", category: "steel", sub_section: "Design & analysis", phase: "SD", text: "Steel grades confirmed (A992 W-shapes, A572 plate, A500 HSS)?" },
  { item_id: "stl-loads", category: "steel", sub_section: "Design & analysis", phase: "DD", text: "Gravity loads applied (dead, live, collateral, snow, MEP allowances)?" },
  { item_id: "stl-lfrs", category: "steel", sub_section: "Design & analysis", phase: "SD", text: "Lateral force-resisting system defined (braced / moment / dual)?" },
  { item_id: "stl-ratios", category: "steel", sub_section: "Design & analysis", phase: "DD", text: "All member utilization ratios ≤ 1.0 (strength)?" },
  { item_id: "stl-defl", category: "steel", sub_section: "Design & analysis", phase: "DD", text: "Deflection limits met (LL L/360, TL L/240, cladding limits)?" },
  { item_id: "stl-vibr", category: "steel", sub_section: "Design & analysis", phase: "DD", text: "Floor vibration / serviceability checked (AISC DG11)?" },
  { item_id: "stl-drift", category: "steel", sub_section: "Design & analysis", phase: "DD", text: "Story / building drift within code & cladding limits?" },
  { item_id: "stl-stab", category: "steel", sub_section: "Design & analysis", phase: "DD", text: "Stability / second-order (P-Δ) effects included per AISC Ch. C?" },
  { item_id: "stl-composite", category: "steel", sub_section: "Design & analysis", phase: "DD", text: "Effect of openings and floor steps on the composite action of beams checked?" },
  { item_id: "stl-seis", category: "steel", sub_section: "Design & analysis", phase: "DD", text: "Seismic detailing (AISC 341) and R / Ω₀ / Cd consistent with the system?" },
  // STEEL - Roof drainage & ponding
  { item_id: "stl-slope", category: "steel", sub_section: "Roof drainage & ponding", phase: "DD", text: "Minimum 1/4 in/ft slope to all roof drains provided?" },
  { item_id: "stl-pond-confirm", category: "steel", sub_section: "Roof drainage & ponding", phase: "DD", text: "Ponding depth around main roof drains and overflows confirmed with the Architect / plumbing engineer?" },
  { item_id: "stl-pond-depth", category: "steel", sub_section: "Roof drainage & ponding", phase: "DD", text: "Is the ponding depth greater than 3 inches?" },
  { item_id: "stl-pond-analysis", category: "steel", sub_section: "Roof drainage & ponding", phase: "DD", text: "Ponding instability analysis performed (or confirmed not required)?" },
  { item_id: "stl-chord", category: "steel", sub_section: "Roof drainage & ponding", phase: "DD", text: "Are perimeter roof chord angles used?" },
  { item_id: "stl-chord-scupper", category: "steel", sub_section: "Roof drainage & ponding", phase: "DD", text: "Perimeter roof chord angle checked against the overflow scupper height for interference?" },
  // STEEL - Diaphragm & detailing
  { item_id: "stl-deck-pattern", category: "steel", sub_section: "Diaphragm & detailing", phase: "DD", text: "Metal deck diaphragm: 36/7 fastener pattern provided in corner and edge zones?" },
  { item_id: "stl-chord-sched", category: "steel", sub_section: "Diaphragm & detailing", phase: "CD", text: "Diaphragm and chord schedules filled out to match the calculations?" },
  { item_id: "stl-ej", category: "steel", sub_section: "Diaphragm & detailing", phase: "DD", text: "Is the expansion joint (EJ) spacing correctly determined and identified in plan?" },
  { item_id: "stl-camber", category: "steel", sub_section: "Diaphragm & detailing", phase: "CD", text: "Camber specified where required?" },
  { item_id: "stl-conn", category: "steel", sub_section: "Diaphragm & detailing", phase: "CD", text: "Connection design scope defined with reactions on drawings?" },

  // BASE PLATES
  { item_id: "bp-thk", category: "baseplates", phase: "DD", text: "Base plate thickness governed by bending checked?" },
  { item_id: "bp-weld", category: "baseplates", phase: "DD", text: "Column-to-base-plate weld designed for demand?" },
  { item_id: "bp-anc", category: "baseplates", phase: "DD", text: "Anchor type, diameter and embedment selected?" },
  { item_id: "bp-tens", category: "baseplates", phase: "DD", text: "Anchor tension / shear interaction checked?" },
  { item_id: "bp-brk", category: "baseplates", phase: "DD", text: "Concrete breakout / pryout / pullout checked (ACI 318 Ch. 17)?" },
  { item_id: "bp-edge", category: "baseplates", phase: "DD", text: "Edge distance & spacing adequate for assumed capacity?" },
  { item_id: "bp-crack", category: "baseplates", phase: "DD", text: "Cracked vs. uncracked concrete assumption documented?" },
  { item_id: "bp-seis", category: "baseplates", phase: "DD", text: "Seismic anchorage provisions / ductility (17.10) satisfied?" },
  { item_id: "bp-si", category: "baseplates", phase: "CD", text: "Special inspection of anchors noted on drawings?" },

  // CONCRETE FRAMES
  { item_id: "cf-fc", category: "concrete", phase: "SD", text: "Concrete strengths f'c defined by element?" },
  { item_id: "cf-rebar", category: "concrete", phase: "SD", text: "Rebar grade and cover defined?" },
  { item_id: "cf-flex", category: "concrete", phase: "DD", text: "Flexure / shear / axial design complete for beams & columns?" },
  { item_id: "cf-joint", category: "concrete", phase: "DD", text: "Beam-column joint shear checked?" },
  { item_id: "cf-dev", category: "concrete", phase: "CD", text: "Development & lap-splice lengths detailed?" },
  { item_id: "cf-defl", category: "concrete", phase: "DD", text: "Long-term deflection / crack control checked?" },
  { item_id: "cf-duct", category: "concrete", phase: "DD", text: "Ductile detailing (ACI 318 Ch. 18) for SDC?" },

  // PRE-CAST
  { item_id: "pc-design", category: "precast", phase: "DD", text: "Pre-cast member design (flexure / shear / handling) complete or clearly delegated?" },
  { item_id: "pc-conn", category: "precast", phase: "DD", text: "Connection design (bearing, ties, corbels) defined?" },
  { item_id: "pc-bearing", category: "precast", phase: "CD", text: "Bearing lengths & support conditions detailed?" },
  { item_id: "pc-topping", category: "precast", phase: "DD", text: "Topping / diaphragm action at pre-cast floor or roof checked?" },
  { item_id: "pc-handle", category: "precast", phase: "CD", text: "Handling / erection / transport stresses addressed (or delegated)?" },
  { item_id: "pc-scope", category: "precast", phase: "DD", text: "Pre-cast scope & delegated-design responsibilities clearly delineated?" },

  // TILT-UP
  { item_id: "tu-oop", category: "tiltup", phase: "DD", text: "Out-of-plane (slender wall, P-Δ) design complete per ACI 318 §11.8?" },
  { item_id: "tu-ip", category: "tiltup", phase: "DD", text: "In-plane shear / overturning of panels checked?" },
  { item_id: "tu-open", category: "tiltup", phase: "DD", text: "Reinforcement around openings / reveals designed?" },
  { item_id: "tu-conn", category: "tiltup", phase: "CD", text: "Panel-to-panel, panel-to-roof and panel-to-footing connections designed?" },
  { item_id: "tu-lift", category: "tiltup", phase: "CD", text: "Lifting / erection stresses addressed (or clearly delegated)?" },
  { item_id: "tu-brace", category: "tiltup", phase: "CD", text: "Temporary bracing noted as deferred / delegated design?" },
  { item_id: "tu-found", category: "tiltup", phase: "DD", text: "Footings under panels sized for panel + tributary loads?" },

  // FOUNDATIONS - Geotech & coordination
  { item_id: "fd-geo", category: "foundations", sub_section: "Geotech & coordination", phase: "SD", text: "Geotechnical report received; bearing / lateral / settlement values captured?" },
  { item_id: "fd-perfletter", category: "foundations", sub_section: "Geotech & coordination", phase: "SD", text: "Geotechnical report follows the AG&E SE Performance Letter?" },
  { item_id: "fd-sog", category: "foundations", sub_section: "Geotech & coordination", phase: "DD", text: "Issuing a slab-on-grade letter discussed with a Principal?" },
  { item_id: "fd-multi", category: "foundations", sub_section: "Geotech & coordination", phase: "DD", text: "Did the geotechnical report provide multiple foundation options?" },
  { item_id: "fd-multi-sel", category: "foundations", sub_section: "Geotech & coordination", phase: "DD", text: "Selected foundation system discussed with the Principal?" },
  { item_id: "fd-subgrade", category: "foundations", sub_section: "Geotech & coordination", phase: "CD", text: "All subgrade preparation notes copied verbatim from the geotechnical report?" },
  { item_id: "fd-mix", category: "foundations", sub_section: "Geotech & coordination", phase: "DD", text: "Concrete mix designs meet the freeze-thaw requirements per code?" },
  { item_id: "fd-cement", category: "foundations", sub_section: "Geotech & coordination", phase: "DD", text: "Geotechnical report reviewed for soil types requiring Type I/II cement, and specified accordingly?" },
  // FOUNDATIONS - Footings
  { item_id: "fd-bear", category: "foundations", sub_section: "Footings", phase: "DD", text: "Footing sizes verified against allowable bearing (service)?" },
  { item_id: "fd-topgrade", category: "foundations", sub_section: "Footings", phase: "DD", text: "Top of footings verified below exterior grades against the grading plan?" },
  { item_id: "fd-frost", category: "foundations", sub_section: "Footings", phase: "DD", text: "Footings verified to bear below the frost depth against the grading plan?" },
  { item_id: "fd-void", category: "foundations", sub_section: "Footings", phase: "DD", text: "Void form depth matches or exceeds the geotechnical report?" },
  { item_id: "fd-ot", category: "foundations", sub_section: "Footings", phase: "DD", text: "Overturning / sliding / uplift checked under lateral combinations?" },
  { item_id: "fd-punch", category: "foundations", sub_section: "Footings", phase: "DD", text: "Punching / one-way shear checked (spread, mat, pile caps)?" },
  { item_id: "fd-reinf", category: "foundations", sub_section: "Footings", phase: "CD", text: "Flexural reinforcement designed & detailed?" },
  { item_id: "fd-deadonly", category: "foundations", sub_section: "Footings", phase: "DD", text: "Footings / piers checked separately for dead load only?" },
  { item_id: "fd-dowels", category: "foundations", sub_section: "Footings", phase: "CD", text: "Pier / footing dowels into the superstructure sized for the required loading?" },
  { item_id: "fd-gb", category: "foundations", sub_section: "Footings", phase: "DD", text: "Grade beams / tie beams designed where required?" },
  { item_id: "fd-ecc", category: "foundations", sub_section: "Footings", phase: "DD", text: "Tilt-wall: footings checked for eccentric loading?" },
  // FOUNDATIONS - Piers / deep foundations
  { item_id: "fd-piers", category: "foundations", sub_section: "Piers / deep foundations", phase: "SD", text: "Does the project use drilled piers / deep foundations?" },
  { item_id: "fd-pile", category: "foundations", sub_section: "Piers / deep foundations", phase: "DD", text: "Pier / pile capacities (axial, lateral, uplift) within geotech limits?" },
  { item_id: "fd-pier-boring", category: "foundations", sub_section: "Piers / deep foundations", phase: "DD", text: "Piers verified not to extend deeper than the boring depths?" },
  { item_id: "fd-pier-rock", category: "foundations", sub_section: "Piers / deep foundations", phase: "DD", text: "Pier penetration into bedrock discounts the top feet per the geotechnical recommendations?" },
  { item_id: "fd-pier-uplift", category: "foundations", sub_section: "Piers / deep foundations", phase: "DD", text: "Piers checked for uplift?" },
  { item_id: "fd-pier-squash", category: "foundations", sub_section: "Piers / deep foundations", phase: "DD", text: "Piers checked for squash loads?" },
  { item_id: "fd-pier-fc", category: "foundations", sub_section: "Piers / deep foundations", phase: "DD", text: "Pier f'c shown matches the squash-load calculations?" },
  { item_id: "fd-pier-aci", category: "foundations", sub_section: "Piers / deep foundations", phase: "DD", text: "Concrete frame: pier f'c verified against ACI 318 Table 19.3.2.1?" },
  { item_id: "fd-pier-anchor", category: "foundations", sub_section: "Piers / deep foundations", phase: "CD", text: "All anchor bolts confirmed to fit within the pier reinforcing cage?" },
  { item_id: "fd-pier-sched", category: "foundations", sub_section: "Piers / deep foundations", phase: "CD", text: "Pier schedule in calculations matches the pier schedule in drawings?" },
  // FOUNDATIONS - Slab & lateral
  { item_id: "fd-slab-lat", category: "foundations", sub_section: "Slab & lateral", phase: "DD", text: "Is the ground floor slab part of the lateral system?" },
  { item_id: "fd-slab-reinf", category: "foundations", sub_section: "Slab & lateral", phase: "DD", text: "Ground floor slab reinforced appropriately for its role in the lateral system?" },
  { item_id: "fd-slab-foot", category: "foundations", sub_section: "Slab & lateral", phase: "DD", text: "Lateral resistance checked in individual footings / piers?" },

  // DRAFTING
  { item_id: "dr-beamtag", category: "drafting", phase: "CD", text: "Are all beams tagged?" },
  { item_id: "dr-foottag", category: "drafting", phase: "CD", text: "Are all footings tagged?" },
  { item_id: "dr-eod", category: "drafting", phase: "CD", text: "Are all EOD (edge-of-deck / slab) dims called out on plans?" },
  { item_id: "dr-beamdims", category: "drafting", phase: "CD", text: "Are dims between beams called out where beam spans are non-uniform between columns?" },
  { item_id: "dr-colelev", category: "drafting", phase: "CD", text: "Are all column bottom elevations equal to the footing top elevations?" },
  { item_id: "dr-dynamo", category: "drafting", phase: "CD", text: "Is the TSD QC-check Dynamo script run?" },
  { item_id: "dr-defldiag", category: "drafting", phase: "CD", text: "Are deflection diagrams created?" },
  { item_id: "dr-defl0", category: "drafting", phase: "CD", text: "Is deflection 0\" at all columns?" },
  { item_id: "dr-grids", category: "drafting", phase: "CD", text: "Are all grids labeled and dimensioned?" },
  { item_id: "dr-sections", category: "drafting", phase: "CD", text: "Do all detail / section call-outs match the cut details?" },
  { item_id: "dr-gennotes", category: "drafting", phase: "DD", text: "Are the general notes current for this phase?" },
  { item_id: "dr-matsched", category: "drafting", phase: "DD", text: "Are the material schedules current for this phase?" },
  { item_id: "dr-title", category: "drafting", phase: "CD", text: "Title block, scale, north arrow & sheet index correct?" },
  { item_id: "dr-revcloud", category: "drafting", phase: "CD", text: "Are revisions clouded & delta-tagged (post-issue)?" },

  // TSD MODEL - Setup & coordination
  { item_id: "tsd-units", category: "tsd", sub_section: "Setup & coordination", phase: "SD", text: "Model units & sign conventions confirmed?" },
  { item_id: "tsd-code", category: "tsd", sub_section: "Setup & coordination", phase: "SD", text: "Design code, ASCE 7 edition & combinations set correctly?" },
  { item_id: "tsd-revit-grids", category: "tsd", sub_section: "Setup & coordination", phase: "DD", text: "Are the elevations and grids equal to Revit?" },
  { item_id: "tsd-revit-base", category: "tsd", sub_section: "Setup & coordination", phase: "DD", text: "Is each column base elevation equal to Revit?" },
  { item_id: "tsd-minsizes", category: "tsd", sub_section: "Setup & coordination", phase: "DD", text: "Are minimum member sizes followed per the AG&E Mission Critical Design Guide?" },
  { item_id: "tsd-self", category: "tsd", sub_section: "Setup & coordination", phase: "DD", text: "Self-weight included once (no double counting)?" },
  { item_id: "tsd-diaph", category: "tsd", sub_section: "Setup & coordination", phase: "DD", text: "Diaphragm type (rigid / semi-rigid) appropriate; deck t_eq applied?" },
  { item_id: "tsd-mass", category: "tsd", sub_section: "Setup & coordination", phase: "DD", text: "Seismic mass / modal results sanity-checked?" },
  { item_id: "tsd-pd", category: "tsd", sub_section: "Setup & coordination", phase: "DD", text: "P-Δ / second-order analysis enabled where required?" },
  { item_id: "tsd-val", category: "tsd", sub_section: "Setup & coordination", phase: "CD", text: "All validation warnings & analysis errors reviewed / resolved?" },
  { item_id: "tsd-draw", category: "tsd", sub_section: "Setup & coordination", phase: "CD", text: "Model geometry reconciled against architectural & drawings?" },
  { item_id: "tsd-revitpush", category: "tsd", sub_section: "Setup & coordination", phase: "CD", text: "Are the correct sizes pushed to Revit via the TSD–Revit link?" },
  // TSD MODEL - Members, materials & releases
  { item_id: "tsd-mat", category: "tsd", sub_section: "Members, materials & releases", phase: "DD", text: "Are all materials correctly set / assigned?" },
  { item_id: "tsd-propsets", category: "tsd", sub_section: "Members, materials & releases", phase: "DD", text: "Are the property sets correctly defined for each member?" },
  { item_id: "tsd-supp", category: "tsd", sub_section: "Members, materials & releases", phase: "DD", text: "Do supports / restraints reflect the real boundary conditions?" },
  { item_id: "tsd-rel", category: "tsd", sub_section: "Members, materials & releases", phase: "DD", text: "Are member releases correctly defined?" },
  { item_id: "tsd-brace", category: "tsd", sub_section: "Members, materials & releases", phase: "DD", text: "Are the brace work points correct?" },
  { item_id: "tsd-topflange", category: "tsd", sub_section: "Members, materials & releases", phase: "DD", text: "For beams not connected to a diaphragm, is the top flange modeled as continuously unbraced?" },
  { item_id: "tsd-momplan", category: "tsd", sub_section: "Members, materials & releases", phase: "CD", text: "Are all moment connections for beams in TSD identified in plan?" },
  { item_id: "tsd-axplan", category: "tsd", sub_section: "Members, materials & releases", phase: "CD", text: "Are all axial releases identified in plan?" },
  // TSD MODEL - Expansion joints
  { item_id: "tsd-ej-has", category: "tsd", sub_section: "Expansion joints", phase: "DD", text: "Does the building have expansion joints (EJs)?" },
  { item_id: "tsd-ej-type", category: "tsd", sub_section: "Expansion joints", phase: "DD", text: "Are the EJs formed by double columns or slide bearings?" },
  { item_id: "tsd-ej-spacing", category: "tsd", sub_section: "Expansion joints", phase: "DD", text: "Is the spacing between the double columns correct?" },
  { item_id: "tsd-ej-rel", category: "tsd", sub_section: "Expansion joints", phase: "DD", text: "Are the EJ releases correctly set?" },
  { item_id: "tsd-ej-slots", category: "tsd", sub_section: "Expansion joints", phase: "CD", text: "Are the slots sized from the maximum deflections and updated on the drawings?" },
  // TSD MODEL - Concrete shear walls
  { item_id: "tsd-sw-model", category: "tsd", sub_section: "Concrete shear walls", phase: "DD", text: "Are all concrete shear walls modeled in TSD?" },
  { item_id: "tsd-sw-open", category: "tsd", sub_section: "Concrete shear walls", phase: "DD", text: "Are the shear-wall openings correctly modeled?" },
  { item_id: "tsd-sw-flat", category: "tsd", sub_section: "Concrete shear walls", phase: "DD", text: "Are all walls connected to the floors / roof using a TSD flat bar?" },
  { item_id: "tsd-sw-base", category: "tsd", sub_section: "Concrete shear walls", phase: "DD", text: "Is the wall base support condition modeled consistently with the details?" },
  // TSD MODEL - Slab on metal deck
  { item_id: "tsd-somd-props", category: "tsd", sub_section: "Slab on metal deck", phase: "DD", text: "Are the slab profile, f'c and diaphragm properties correctly set for the SOMD?" },
  { item_id: "tsd-somd-span", category: "tsd", sub_section: "Slab on metal deck", phase: "DD", text: "Is the span direction consistent with the drawings?" },
  { item_id: "tsd-somd-sep", category: "tsd", sub_section: "Slab on metal deck", phase: "DD", text: "Are the slabs separated at each bay?" },
  { item_id: "tsd-somd-open", category: "tsd", sub_section: "Slab on metal deck", phase: "DD", text: "Are all slab openings modeled, with framing around them?" },
  { item_id: "tsd-somd-over", category: "tsd", sub_section: "Slab on metal deck", phase: "DD", text: "Are all slab overhangs modeled correctly per the drawings?" },
  // TSD MODEL - Footings
  { item_id: "tsd-ft-support", category: "tsd", sub_section: "Footings", phase: "DD", text: "Are the correct footing / support types assigned at each column base?" },
  { item_id: "tsd-ft-fixity", category: "tsd", sub_section: "Footings", phase: "DD", text: "Are support fixities (pinned / fixed) consistent with the foundation details?" },
  { item_id: "tsd-ft-react", category: "tsd", sub_section: "Footings", phase: "DD", text: "Are the design reactions exported for foundation design at the correct load combinations?" },
  { item_id: "tsd-ft-uplift", category: "tsd", sub_section: "Footings", phase: "DD", text: "Are uplift / net-tension reactions at footings flagged and addressed?" },

  // RISAFOUNDATION
  { item_id: "rf-import", category: "risafoundation", phase: "DD", text: "Column / wall reactions imported correctly from the superstructure?" },
  { item_id: "rf-soil", category: "risafoundation", phase: "DD", text: "Soil spring / bearing (subgrade modulus) input per geotech?" },
  { item_id: "rf-combos", category: "risafoundation", phase: "DD", text: "Load combinations match the governing code set?" },
  { item_id: "rf-mesh", category: "risafoundation", phase: "DD", text: "Mesh density adequate (convergence checked for mats)?" },
  { item_id: "rf-soilp", category: "risafoundation", phase: "DD", text: "Soil bearing pressures within allowable (no / limited uplift)?" },
  { item_id: "rf-results", category: "risafoundation", phase: "CD", text: "Reinforcement results transferred to drawings & rounded sensibly?" },

  // HILTI PROFIS
  { item_id: "hp-prod", category: "hilti", phase: "DD", text: "Correct anchor product & approval (ESR / code) selected?" },
  { item_id: "hp-loads", category: "hilti", phase: "DD", text: "Applied loads match base-plate reactions (correct combos)?" },
  { item_id: "hp-crack", category: "hilti", phase: "DD", text: "Concrete condition (cracked / uncracked) set correctly?" },
  { item_id: "hp-edge", category: "hilti", phase: "DD", text: "Edge distances, spacing & member thickness match the real condition?" },
  { item_id: "hp-seis", category: "hilti", phase: "DD", text: "Seismic design option enabled where applicable?" },
  { item_id: "hp-report", category: "hilti", phase: "CD", text: "Final PROFIS report saved to the project folder?" },

  // SPWALL
  { item_id: "sw-geom", category: "spwall", phase: "DD", text: "Wall geometry, thickness & f'c entered correctly?" },
  { item_id: "sw-loads", category: "spwall", phase: "DD", text: "Axial, in-plane shear & out-of-plane moments match the model?" },
  { item_id: "sw-reinf", category: "spwall", phase: "DD", text: "Reinforcement layout (curtains, boundary elements) defined?" },
  { item_id: "sw-pm", category: "spwall", phase: "DD", text: "P-M interaction & demand points within the capacity envelope?" },
  { item_id: "sw-slen", category: "spwall", phase: "DD", text: "Slenderness / second-order effects considered?" },
  { item_id: "sw-crack", category: "spwall", phase: "CD", text: "Crack width / deflection serviceability acceptable?" },
];

export const CATEGORIES = [
  { id: "general",          label: "General" },
  { id: "metaldeck",        label: "Metal Deck / Diaphragm" },
  { id: "compositedeck",    label: "Composite Deck (Floor)" },
  { id: "steel",            label: "Steel Structure" },
  { id: "baseplates",       label: "Base Plates / Anchorage" },
  { id: "concrete",         label: "Concrete Frames (CIP)" },
  { id: "precast",          label: "Pre-Cast" },
  { id: "tiltup",           label: "Tilt-Up" },
  { id: "foundations",      label: "Foundations" },
  { id: "drafting",         label: "Drafting" },
  { id: "tsd",              label: "TSD Model (Tekla)" },
  { id: "risafoundation",   label: "RISAFoundation" },
  { id: "hilti",            label: "Hilti PROFIS" },
  { id: "spwall",           label: "spWall" },
  { id: "project_specific", label: "Project Specific" },
];